[package]
name = "odeint"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.17.2"
num-complex = "0.4.6"
thiserror = "2.0.18"

[profile.dev]
opt-level = 0
debug = 2
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
debug = true
split-debuginfo = "unpacked"